// use("ecommerce");

// db.products.insertMany([
//   {
//     productId: "P001",
//     name: "Gaming Laptop",
//     brand: "ASUS",
//     category: "Laptop",
//     price: 165000,
//     stock: 12,
//     rating: 4.8,
//     discount: 10,
//     tags: ["gaming", "RTX", "16GB RAM"],
//     specifications: {
//       cpu: "Intel i7",
//       ram: "16GB",
//       storage: "1TB SSD",
//     },
//   },
//   {
//     productId: "P002",
//     name: "Wireless Mouse",
//     brand: "Logitech",
//     category: "Accessories",
//     price: 4500,
//     stock: 35,
//     rating: 4.6,
//     discount: 15,
//     tags: ["wireless", "Bluetooth", "ergonomic"],
//     specifications: {
//       dpi: "1600",
//       connectivity: "Bluetooth",
//       battery: "AA",
//     },
//   },
//   {
//     productId: "P003",
//     name: "Mechanical Keyboard",
//     brand: "Redragon",
//     category: "Accessories",
//     price: 8500,
//     stock: 20,
//     rating: 4.7,
//     discount: 12,
//     tags: ["RGB", "Mechanical", "Gaming"],
//     specifications: {
//       switch: "Blue",
//       connectivity: "USB",
//       lighting: "RGB",
//     },
//   },
//   {
//     productId: "P004",
//     name: "Gaming Monitor",
//     brand: "MSI",
//     category: "Monitor",
//     price: 52000,
//     stock: 8,
//     rating: 4.9,
//     discount: 8,
//     tags: ["144Hz", "IPS", "27-inch"],
//     specifications: {
//       resolution: "1920x1080",
//       refreshRate: "144Hz",
//       panel: "IPS",
//     },
//   },
//   {
//     productId: "P005",
//     name: "Smartphone",
//     brand: "Samsung",
//     category: "Mobile",
//     price: 89000,
//     stock: 18,
//     rating: 4.5,
//     discount: 5,
//     tags: ["5G", "AMOLED", "128GB"],
//     specifications: {
//       processor: "Snapdragon 8 Gen 2",
//       ram: "8GB",
//       storage: "128GB",
//     },
//   },
//   {
//     productId: "P006",
//     name: "Bluetooth Speaker",
//     brand: "JBL",
//     category: "Audio",
//     price: 12000,
//     stock: 25,
//     rating: 4.6,
//     discount: 18,
//     tags: ["Portable", "Bass", "Waterproof"],
//     specifications: {
//       battery: "12 Hours",
//       connectivity: "Bluetooth 5.3",
//       waterproof: "IPX7",
//     },
//   },
//   {
//     productId: "P007",
//     name: "Smart Watch",
//     brand: "Huawei",
//     category: "Wearables",
//     price: 28000,
//     stock: 14,
//     rating: 4.4,
//     discount: 10,
//     tags: ["Fitness", "GPS", "Heart Rate"],
//     specifications: {
//       display: "1.43-inch AMOLED",
//       battery: "14 Days",
//       sensors: "Heart Rate, SpO2",
//     },
//   },
//   {
//     productId: "P008",
//     name: "External SSD",
//     brand: "Samsung",
//     category: "Storage",
//     price: 18500,
//     stock: 30,
//     rating: 4.8,
//     discount: 7,
//     tags: ["1TB", "USB-C", "Portable"],
//     specifications: {
//       capacity: "1TB",
//       interface: "USB-C",
//       speed: "1050 MB/s",
//     },
//   },
//   {
//     productId: "P009",
//     name: "Wireless Earbuds",
//     brand: "Anker",
//     category: "Audio",
//     price: 9500,
//     stock: 40,
//     rating: 4.5,
//     discount: 20,
//     tags: ["TWS", "Noise Cancellation", "Bluetooth"],
//     specifications: {
//       battery: "30 Hours",
//       connectivity: "Bluetooth 5.2",
//       charging: "USB-C",
//     },
//   },
//   {
//     productId: "P010",
//     name: "Tablet",
//     brand: "Apple",
//     category: "Tablet",
//     price: 135000,
//     stock: 10,
//     rating: 4.9,
//     discount: 5,
//     tags: ["iPad", "Retina", "WiFi"],
//     specifications: {
//       processor: "Apple M2",
//       storage: "256GB",
//       display: "11-inch Liquid Retina",
//     },
//   },
// ]);

use("ecommerce");

db.orders.insertMany([
  {
    orderId: "ORD001",
    customer: "Ali Khan",
    products: [
      { productId: "P001", quantity: 1, price: 165000 },
      { productId: "P002", quantity: 2, price: 4500 },
    ],
    paymentMethod: "Card",
    status: "Delivered",
    total: 174000,
  },
  {
    orderId: "ORD002",
    customer: "Ahmed Raza",
    products: [
      { productId: "P003", quantity: 1, price: 8500 },
      { productId: "P009", quantity: 1, price: 9500 },
      { productId: "P002", quantity: 1, price: 4500 },
    ],
    paymentMethod: "Cash",
    status: "Pending",
    total: 22500,
  },
  {
    orderId: "ORD003",
    customer: "Sara Khan",
    products: [
      { productId: "P005", quantity: 1, price: 89000 },
      { productId: "P009", quantity: 2, price: 9500 },
    ],
    paymentMethod: "Card",
    status: "Delivered",
    total: 108000,
  },
  {
    orderId: "ORD004",
    customer: "Usman Ali",
    products: [
      { productId: "P004", quantity: 1, price: 52000 },
      { productId: "P003", quantity: 1, price: 8500 },
      { productId: "P002", quantity: 2, price: 4500 },
    ],
    paymentMethod: "JazzCash",
    status: "Shipped",
    total: 69500,
  },
  {
    orderId: "ORD005",
    customer: "Ayesha Noor",
    products: [
      { productId: "P010", quantity: 1, price: 135000 },
      { productId: "P008", quantity: 1, price: 18500 },
    ],
    paymentMethod: "Card",
    status: "Delivered",
    total: 153500,
  },
  {
    orderId: "ORD006",
    customer: "Bilal Ahmed",
    products: [
      { productId: "P006", quantity: 2, price: 12000 },
      { productId: "P009", quantity: 1, price: 9500 },
    ],
    paymentMethod: "Cash",
    status: "Cancelled",
    total: 33500,
  },
  {
    orderId: "ORD007",
    customer: "Fatima Ali",
    products: [
      { productId: "P007", quantity: 1, price: 28000 },
      { productId: "P008", quantity: 1, price: 18500 },
      { productId: "P002", quantity: 1, price: 4500 },
    ],
    paymentMethod: "EasyPaisa",
    status: "Processing",
    total: 51000,
  },
  {
    orderId: "ORD008",
    customer: "Hamza Khan",
    products: [
      { productId: "P001", quantity: 1, price: 165000 },
      { productId: "P006", quantity: 1, price: 12000 },
      { productId: "P003", quantity: 1, price: 8500 },
    ],
    paymentMethod: "Card",
    status: "Delivered",
    total: 185500,
  },
  {
    orderId: "ORD009",
    customer: "Zain Ali",
    products: [
      { productId: "P005", quantity: 1, price: 89000 },
      { productId: "P007", quantity: 1, price: 28000 },
      { productId: "P009", quantity: 2, price: 9500 },
    ],
    paymentMethod: "Bank Transfer",
    status: "Shipped",
    total: 136000,
  },
  {
    orderId: "ORD010",
    customer: "Hira Malik",
    products: [
      { productId: "P004", quantity: 1, price: 52000 },
      { productId: "P010", quantity: 1, price: 135000 },
      { productId: "P002", quantity: 1, price: 4500 },
      { productId: "P003", quantity: 1, price: 8500 },
    ],
    paymentMethod: "Card",
    status: "Delivered",
    total: 200000,
  },
]);
